### ISSUE TITLE
Merge: exception has occured

### ISSUE THREAD

**Issue by Pheil** [murrty/youtube-dl-gui#102]
When trying to merge an mp4 and m4a I get this error.

rtbExceptionDetails

Version: 2.262
An exception occured
Message: The system cannot find the file specified
Stacktrace:    at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at youtube_dl_gui.Convert.mergeFiles(String input1, String input2, String output, Boolean mergeAudio, Boolean deleteAfterMerge)
Source: System
Target Site: Boolean StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo)
Full report:
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at youtube_dl_gui.Convert.mergeFiles(String input1, String input2, String output, Boolean mergeAudio, Boolean deleteAfterMerge)

**Comment by murrty** [comment]
Merging files require ffmpeg.

**Comment by Pheil** [comment]
Maybe different issue ?  I set the ffmpeg directory then confirm that the setting is saved in the ini (ffmpegPath=C:\Program Files\ffmpeg\bin), but when I go back into settings the path field is blank.

**Comment by murrty** [comment]
I caught a bug where merging wouldn't work because it wasn't checking the verification path of ffmpeg, instead calling it straight-out like command line. Also, there's a dedicated merging form now which is preferred.

If it persists, re-open.
