### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by KalpanaChetan** [murrty/youtube-dl-gui#155]
An unhandled thread exception occurred.
The application will exit after closing this dialog.

System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at youtube_dl_gui.Verification.RefreshYoutubeDlLocation()
   at youtube_dl_gui.frmSettings.saveSettings()
   at youtube_dl_gui.frmSettings.btnSettingsSave_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

========== FULL REPORT ==========
System.Threading.ThreadExceptionEventArgs
========== END  REPORT ==========

========== OS  INFO ==========
(Please don't omit this info, it may be important)
Current version: 3.1.1
Curernt culture: English (United Kingdom)
System Caption: Microsoft Windows 10 Pro
Version: 10.0.19044
Service Pack Major: 0
Service Pack Minor: 0
========== END INFO ==========

**Comment by murrty** [comment]
Are you using youtube-dl or yt-dlp? If you're using youtube-dl does the file name match `youtube-dl.exe`? If you're using yt-dlp, does the file name match `yt-dlp.exe`?

**Comment by KalpanaChetan** [comment]
![Screenshot (46).png](https://user-images.githubusercontent.com/112402936/198930243-fa788790-d0a1-4a09-8d0f-2d80e09c6826.png)

**Comment by murrty** [comment]
[youtube-dl-gui.zip](https://github.com/murrty/youtube-dl-gui/files/9898753/youtube-dl-gui.zip)
Try this build, I think it should be solved.

**Comment by KalpanaChetan** [comment]
other problem




A caught IOException occured.

Message: The process cannot access the file 'C:\Users\NAGAE\Downloads\youtube-dl-gui\ffmpeg.exe' because it is being used by another process.
Stacktrace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.OpenFile(String path, FileAccess access, SafeFileHandle& handle)
   at System.IO.File.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at youtube_dl_gui.UpdateChecker.UpdateFfmpeg(Nullable`1 Location)
Source: mscorlib
Target Site: Void WinIOError(Int32, System.String)
Inner Exception: 

========== FULL REPORT ==========
System.IO.IOException: The process cannot access the file 'C:\Users\NAGAE\Downloads\youtube-dl-gui\ffmpeg.exe' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.OpenFile(String path, FileAccess access, SafeFileHandle& handle)
   at System.IO.File.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at youtube_dl_gui.UpdateChecker.UpdateFfmpeg(Nullable`1 Location)
========== END  REPORT ==========

========== OS  INFO ==========
(Please don't omit this info, it may be important)
Current version: 3.1.1
Curernt culture: English (United Kingdom)
System Caption: Microsoft Windows 10 Pro
Version: 10.0.19044
Service Pack Major: 0
Service Pack Minor: 0
========== END INFO ==========

**Comment by murrty** [comment]
another program is taking control of ffmpeg, either a anti-virus or something else scanning it.
