### ISSUE TITLE
Updater throws exception

### ISSUE THREAD

**Issue by coastercrab** [murrty/youtube-dl-gui#161]
Inner Exception: 
Response: 

========== FULL REPORT ==========
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at murrty.classcontrols.ExtendedWebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at youtube_dl_gui_updater.frmUpdater.<<SetDownloadThread>b__7_0>d.MoveNext()
========== END  REPORT ==========

========== OS  INFO ==========
(Please don't omit this info, it may be important)
Not initialized
========== END INFO ==========

**Comment by murrty** [comment]
Are you running on Windows 7 or below?
