### ISSUE TITLE
Error upon opening

### ISSUE THREAD

**Issue by wingzeroalchemist** [murrty/youtube-dl-gui#181]
Feel free to copy + paste this entire text wall into a new issue on Github

Version: 2.252
Reported Exception: An exception occured
Message: Input string was not in a correct format.
Stacktrace:    at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseDecimal(String value, NumberStyles options, NumberFormatInfo numfmt)
   at youtube_dl_gui.GitData.GitLinks.GetGitVersionDecimal(String InputVersion)
   at youtube_dl_gui.UpdateChecker.GetGitVersion(Int32 GitID)
Source: mscorlib
TargetSite: Void StringToNumber(System.String, System.Globalization.NumberStyles, NumberBuffer ByRef, System.Globalization.NumberFormatInfo, Boolean)
Full report:
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseDecimal(String value, NumberStyles options, NumberFormatInfo numfmt)
   at youtube_dl_gui.GitData.GitLinks.GetGitVersionDecimal(String InputVersion)
   at youtube_dl_gui.UpdateChecker.GetGitVersion(Int32 GitID)

**Comment by murrty** [comment]
This is because the version styling was changed and it cannot parse the new versions. You either have to disable update checking if you want to stay on that version or download version 3.0 (or the latest release, which would be a better idea)
