### ISSUE TITLE
"A caught WebException occurred."

### ISSUE THREAD

**Issue by danepedersen** [murrty/youtube-dl-gui#189]
A caught WebException occurred.

Message: The remote name could not be resolved: 'api.github.com'
Type: System.Net.WebException
Response: 
Source: System
Target Site: Byte[] DownloadDataInternal(System.Uri, System.Net.WebRequest ByRef)
Stacktrace:
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at youtube_dl_gui.UpdateChecker.GetJSON(String Url)
   at youtube_dl_gui.UpdateChecker.RefreshRelease(Version CurrentVersion, Boolean PreReleases)
   at youtube_dl_gui.UpdateChecker.CheckForUpdate(Boolean ForceCheck, Boolean AllowSkip, Form ParentHandle)

========== OS  INFO ==========
Current Version: 3.3.0-1
Current Culture: English (Canada)
System Caption: Microsoft Windows 11 Pro
System Version: 10.0.22621
Service Pack Major: 0
Service Pack Minor: 0
========== END INFO ==========

**Comment by murrty** [comment]
Does this still occur for you? It looks like a problem on your end since the update checks work on my side.

**Comment by nai888** [comment]
I ran into this issue at first. Running as an administrator fixed it.

**Comment by danepedersen** [comment]
Ah, good to know - thank you!
