### ISSUE TITLE
I got thir error while downloading 

### ISSUE THREAD

**Issue by bagajohny** [murrty/youtube-dl-gui#192]
A caught IndexOutOfRangeException occurred.

Message: Index was outside the bounds of the array.
Type: System.IndexOutOfRangeException
Source: System.Windows.Forms
Target Site: System.Object MarshaledInvoke(System.Windows.Forms.Control, System.Delegate, System.Object[], Boolean)
Stacktrace:
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at youtube_dl_gui.frmDownloader.<>c__DisplayClass12_0.<BeginDownload>b__0()

========== OS  INFO ==========
Current Version: 3.2.3
Current Culture: English (United Kingdom)
System Caption: Microsoft Windows 10 IoT Enterprise LTSC
System Version: 10.0.19044
Service Pack Major: 0
Service Pack Minor: 0
========== END INFO ==========

**Comment by murrty** [comment]
What kind of settings were you using?

**Comment by bagajohny** [comment]
I was using default settings. Anyway, I used a different downloader so now I am no longer in the need. You can close the issue if you want.

**Comment by DvarfInkviz** [comment]
> I was using default settings. Anyway, I used a different downloader so now I am no longer in the need. You can close the issue if you want.

Could you say which another downloader you're using now?
